import { CLIENT_CONFIG } from './env';

// API configuration
export const API_BASE_URL = CLIENT_CONFIG.apiBaseUrl;

import { createAuthFetchOptions } from './auth-utils';

// Helper function to make API requests
export async function apiRequest<T>(
  endpoint: string,
  options: RequestInit = {}
): Promise<T> {
  const url = `${API_BASE_URL}${endpoint}`;
  
  const response = await fetch(url, 
    createAuthFetchOptions(options)
  );

  if (!response.ok) {
    throw new Error(`API request failed: ${response.status} ${response.statusText}`);
  }

  return response.json();
}

// API endpoints
export const API_ENDPOINTS = {
  apiHealth: "/health",
  
  // Authentication & User Management
  authSendCode: "/api/auth/send-code",
  authVerifyCode: "/api/auth/verify-code",
  authRegister: "/api/auth/register",
  authCompleteOnboarding: "/api/auth/complete-onboarding",
  authProfileCompletionStatus: "/api/auth/profile-completion-status",
  authProfileCompleteness: "/api/auth/profile-completeness",
  authMe: "/api/auth/me",
  authProfile: "/api/auth/profile",
  authUploadAvatar: "/api/auth/upload-avatar",
  authUploadPortfolio: "/api/auth/upload-portfolio",
  authLogout: "/api/auth/logout",
  
  // Marketplace Services
  marketplaceServices: "/api/marketplace/services",
  marketplaceServiceById: "/api/marketplace/services",
  marketplaceServiceDeactivate: "/api/marketplace/services",
  marketplaceServiceActivate: "/api/marketplace/services",
  marketplaceServicesCategories: "/api/marketplace/services/categories",
  marketplaceMyServices: "/api/marketplace/my-services",
  marketplaceMyBookings: "/api/marketplace/my-bookings",
  marketplaceBookings: "/api/marketplace/bookings",
  marketplaceBookingStatus: "/api/marketplace/bookings",
  marketplaceBookingPhotos: "/api/marketplace/bookings",
  marketplaceBookingReview: "/api/marketplace/bookings",
  marketplacePayPalApprove: "/api/marketplace/bookings/paypal/approve",
  marketplacePayPalOrder: "/api/marketplace/bookings/paypal/order",
  marketplaceListings: "/api/marketplace/services",
  marketplaceProvidersWithService: "/api/marketplace/services/[id]/providers",
  marketplaceServicesCategoriesById: "/api/marketplace/services/categories/[id]",
  marketplaceProvidersById: "/api/marketplace/providers/[id]",
  marketplaceProvidersServices: "/api/marketplace/providers/[id]/services",
  
  // AI Features
  aiNaturalLanguageSearch: "/api/ai/marketplace/natural-language-search",
  aiServiceRecommendations: "/api/ai/marketplace/recommendations",
  aiPriceEstimator: "/api/ai/marketplace/price-estimator",
  aiServiceMatcher: "/api/ai/marketplace/service-matcher",
  aiReviewSentiment: "/api/ai/marketplace/review-sentiment",
  aiBookingAssistant: "/api/ai/marketplace/booking-assistant",
  aiDescriptionGenerator: "/api/ai/marketplace/description-generator",
  aiDescriptionFromTitle: "/api/ai/marketplace/description-from-title",
  aiPricingOptimizer: "/api/ai/marketplace/pricing-optimizer",
  aiDemandForecast: "/api/ai/marketplace/demand-forecast",
  aiReviewInsights: "/api/ai/marketplace/review-insights",
  aiResponseAssistant: "/api/ai/marketplace/response-assistant",
  aiListingOptimizer: "/api/ai/marketplace/listing-optimizer",
  aiSchedulingAssistant: "/api/ai/marketplace/scheduling-assistant",
  aiBioGenerator: "/api/ai/users/bio-generator",
  aiFormPrefiller: "/api/ai/marketplace/form-prefiller",

  
  // Job Board
  jobs: "/api/jobs",
  jobsSearch: "/api/jobs/search",
  jobsById: "/api/jobs",
  jobsCategories: "/api/jobs/categories",
  jobsMyApplications: "/api/jobs/my-applications",
  jobsMyJobs: "/api/jobs/my-jobs",
  jobsApply: "/api/jobs",
  jobsStats: "/api/jobs",
  jobsApplications: "/api/jobs",
  jobsApplicationStatus: "/api/jobs",
  jobsLogo: "/api/jobs",
  jobsApplicationsById: "/api/jobs",
  
  // Academy & Learning
  academyCourses: "/api/academy/courses",
  academyCourseById: "/api/academy/courses",
  academyCategories: "/api/academy/categories",
  academyFeatured: "/api/academy/featured",
  academyMyCourses: "/api/academy/my-courses",
  academyMyCreatedCourses: "/api/academy/my-created-courses",
  academyCourseThumbnail: "/api/academy/courses",
  academyCourseVideos: "/api/academy/courses",
  academyCourseVideoDelete: "/api/academy/courses",
  academyEnroll: "/api/academy/courses",
  academyProgress: "/api/academy/courses",
  academyReviews: "/api/academy/courses",
  academyCoursesEnroll: "/api/academy/courses/[id]/enroll",
  academyCoursesProgress: "/api/academy/courses/[id]/progress",
  academyCoursesReviews: "/api/academy/courses/[id]/reviews",
  academyCoursesThumbnail: "/api/academy/courses/[id]/thumbnail",
  academyCoursesVideosById: "/api/academy/courses/[id]/videos/[videoId]",
  academyCoursesVideos: "/api/academy/courses/[id]/videos",
  academyCoursesById: "/api/academy/courses",
  academyStatistics: "/api/academy/statistics",
  academyCourseCreate: "/api/academy/courses",
  academyCourseUpdate: "/api/academy/courses",
  academyCourseDelete: "/api/academy/courses",
  academyCourseVideo: "/api/academy/courses",
  
  // Supplies & Equipment
  supplies: "/api/supplies",
  suppliesById: "/api/supplies/[id]",
  suppliesItems: "/api/supplies/items",
  suppliesProducts: "/api/supplies/products",
  suppliesProductsById: "/api/supplies/products/[id]",
  suppliesCategories: "/api/supplies/categories",
  suppliesTypes: "/api/supplies/types",
  suppliesStatuses: "/api/supplies/statuses",
  suppliesFeatured: "/api/supplies/featured",
  suppliesNearby: "/api/supplies/nearby",
  suppliesMySupplies: "/api/supplies/my-supplies",
  suppliesMyOrders: "/api/supplies/my-orders",
  suppliesImages: "/api/supplies",
  suppliesImageDelete: "/api/supplies",
  suppliesOrder: "/api/supplies",
  suppliesOrderStatus: "/api/supplies",
  suppliesReviews: "/api/supplies",
  suppliesCreate: "/api/supplies",
  suppliesUpdate: "/api/supplies",
  suppliesDelete: "/api/supplies",
  suppliesStatistics: "/api/supplies/statistics",
  
  // Equipment Rentals
  rentals: "/api/rentals",
  rentalsCategories: "/api/rentals/categories",
  rentalsFeatured: "/api/rentals/featured",
  rentalsNearby: "/api/rentals/nearby",
  rentalsById: "/api/rentals",
  rentalsMyRentals: "/api/rentals/my-rentals",
  rentalsMyBookings: "/api/rentals/my-bookings",
  rentalsImages: "/api/rentals",
  rentalsImageDelete: "/api/rentals",
  rentalsBook: "/api/rentals",
  rentalsBookingStatus: "/api/rentals",
  rentalsReviews: "/api/rentals",
  rentalsStatistics: "/api/rentals/statistics",
  rentalsItems: "/api/rentals/items",
  rentalsItemsById: "/api/rentals/items",
  rentalsCreate: "/api/rentals",
  rentalsUpdate: "/api/rentals",
  rentalsDelete: "/api/rentals",
  rentalsGenerateDescription: "/api/rentals/generate-description",
  
  // Facility Care Services
  facilityCare: "/api/facility-care",
  facilityCareNearby: "/api/facility-care/nearby",
  facilityCareById: "/api/facility-care",
  facilityCareMyServices: "/api/facility-care/my-services",
  facilityCareMyBookings: "/api/facility-care/my-bookings",
  facilityCareImages: "/api/facility-care",
  facilityCareImageDelete: "/api/facility-care",
  facilityCareBook: "/api/facility-care",
  facilityCareBookingStatus: "/api/facility-care",
  facilityCareReviews: "/api/facility-care",
  facilityCareCreate: "/api/facility-care",
  facilityCareUpdate: "/api/facility-care",
  facilityCareDelete: "/api/facility-care",
  facilityCareStatistics: "/api/facility-care/statistics",
  
  // Communication & Messaging
  communicationConversations: "/api/communication/conversations",
  communicationConversationById: "/api/communication/conversations",
  communicationConversationsMessagesById: "/api/communication/conversations/[id]/messages/[messageId]",
  communicationConversationsMessages: "/api/communication/conversations/[id]/messages",
  communicationConversationsRead: "/api/communication/conversations/[id]/read",
  communicationConversationsById: "/api/communication/conversations/[id]",
  communicationMessages: "/api/communication/conversations",
  communicationMessageUpdate: "/api/communication/conversations",
  communicationMessageDelete: "/api/communication/conversations",
  communicationRead: "/api/communication/conversations",
  communicationNotifications: "/api/communication/notifications",
  communicationNotificationCount: "/api/communication/notifications/count",
  communicationNotificationRead: "/api/communication/notifications",
  communicationNotificationReadAll: "/api/communication/notifications/read-all",
  communicationNotificationDelete: "/api/communication/notifications",
  communicationNotificationsReadAll: "/api/communication/notifications/read-all",
  communicationNotificationsRead: "/api/communication/notifications/[id]/read",
  communicationNotificationsById: "/api/communication/notifications/[id]",
  communicationEmailNotification: "/api/communication/notifications/email",
  communicationSmsNotification: "/api/communication/notifications/sms",
  communicationUnreadCount: "/api/communication/unread-count",
  communicationSearch: "/api/communication/search",
  communicationConversationWith: "/api/communication/conversation-with",
  communicationEvents: "/api/communication/events",
  communicationTyping: "/api/communication/typing",
  communicationTest: "/api/communication/test",
  
  // Advertising & Promotions
  ads: "/api/ads",
  adsCategories: "/api/ads/categories",
  adsFeatured: "/api/ads/featured",
  adsById: "/api/ads",
  adsClick: "/api/ads",
  adsMyAds: "/api/ads/my-ads",
  adsImages: "/api/ads",
  adsImageDelete: "/api/ads",
  adsPromote: "/api/ads",
  adsAnalytics: "/api/ads",
  adsStatistics: "/api/ads/statistics",
  adsPending: "/api/ads/pending",
  adsApprove: "/api/ads",
  adsReject: "/api/ads",
  adsEnumValues: "/api/ads/enum-values",
  adsCreate: "/api/ads",
  adsUpdate: "/api/ads",
  adsDelete: "/api/ads",
  analyticsCustom: "/api/analytics/custom",
  
  // Trust & Verification
  trustVerificationVerifiedUsers: "/api/trust-verification/verified-users",
  trustVerificationRequests: "/api/trust-verification/requests",
  trustVerificationRequestById: "/api/trust-verification/requests",
  trustVerificationRequestDocuments: "/api/trust-verification/requests",
  trustVerificationDocumentDelete: "/api/trust-verification/requests",
  trustVerificationMyRequests: "/api/trust-verification/my-requests",
  trustVerificationCreate: "/api/trust-verification/requests",
  trustVerificationUpdate: "/api/trust-verification/requests",
  trustVerificationDelete: "/api/trust-verification/requests",
  trustVerificationReview: "/api/trust-verification/requests",
  trustVerificationStatistics: "/api/trust-verification/statistics",
  
  // Referral System
  referralsValidate: "/api/referrals/validate",
  referralsTrack: "/api/referrals/track",
  referralsLeaderboard: "/api/referrals/leaderboard",
  referralsMe: "/api/referrals/me",
  referralsStats: "/api/referrals/stats",
  referralsLinks: "/api/referrals/links",
  referralsRewards: "/api/referrals/rewards",
  referralsInvite: "/api/referrals/invite",
  referralsPreferences: "/api/referrals/preferences",
  referralsProcess: "/api/referrals/process",
  referralsAnalytics: "/api/referrals/analytics",
  
  // Financial Management
  financeOverview: "/api/finance/overview",
  financeTransactions: "/api/finance/transactions",
  financeEarnings: "/api/finance/earnings",
  financeExpenses: "/api/finance/expenses",
  financeReports: "/api/finance/reports",
  financeExpenseAdd: "/api/finance/expenses",
  financeWithdraw: "/api/finance/withdraw",
  financeTaxDocuments: "/api/finance/tax-documents",
  financeWalletSettings: "/api/finance/wallet/settings",
  financeWithdrawalsProcess: "/api/finance/withdrawals",
  financeTopUp: "/api/finance/top-up",
  financeTopUps: "/api/finance/top-ups",
  financeTopUpsMyRequests: "/api/finance/top-ups/my-requests",
  financeTopUpProcess: "/api/finance/top-ups",
  
  // Google Maps Integration
  maps: "/api/maps",
  mapsGeocode: "/api/maps/geocode",
  mapsReverseGeocode: "/api/maps/reverse-geocode",
  mapsPlacesSearch: "/api/maps/places/search",
  mapsPlaceById: "/api/maps/places",
  mapsDistance: "/api/maps/distance",
  mapsNearby: "/api/maps/nearby",
  mapsValidateServiceArea: "/api/maps/validate-service-area",
  mapsAnalyzeCoverage: "/api/maps/analyze-coverage",
  mapsTest: "/api/maps/test",
  
  // PayPal Integration
  paypalWebhook: "/api/paypal/webhook",
  paypalWebhookEvents: "/api/paypal/webhook/events",
  
  // PayMaya Integration
  paymayaWebhook: "/api/paymaya/webhook",
  paymayaCheckout: "/api/paymaya/checkout",
  paymayaCheckoutById: "/api/paymaya/checkout",
  paymayaPayment: "/api/paymaya/payment",
  paymayaPaymentById: "/api/paymaya/payment",
  paymayaInvoice: "/api/paymaya/invoice",
  paymayaInvoiceById: "/api/paymaya/invoice",
  paymayaConfigValidate: "/api/paymaya/config/validate",
  paymayaWebhookEvents: "/api/paymaya/webhook/events",
  
  // Provider Management
  providers: "/api/providers",
  providersProfileMe: "/api/providers/profile/me",
  providersProfile: "/api/providers/profile",
  providersOnboardingStep: "/api/providers/onboarding/step",
  providersDocumentsUpload: "/api/providers/documents/upload",
  providersDashboard: "/api/providers/dashboard/overview",
  providersAnalytics: "/api/providers/analytics/performance",
  providersDashboardOverview: "/api/providers/dashboard/overview",
  providersAnalyticsPerformance: "/api/providers/analytics/performance",
  providersAdminAll: "/api/providers/admin/all",
  providersAdminStatus: "/api/providers/admin",
  providersSkills: "/api/providers/skills",
  providersSkillsByCategory: "/api/providers/skills", // Use query parameter: ?category=cleaning
  providersById: "/api/providers/[id]",
  providersAdminStatusById: "/api/providers/admin/[id]/status",
  
  // Agency Management
  agencies: "/api/agencies",
  agenciesById: "/api/agencies",
  agenciesLogo: "/api/agencies",
  agenciesProviders: "/api/agencies",
  agenciesProviderDelete: "/api/agencies",
  agenciesProviderStatus: "/api/agencies",
  agenciesAdmins: "/api/agencies",
  agenciesAdminDelete: "/api/agencies",
  agenciesAnalytics: "/api/agencies",
  agenciesMyAgencies: "/api/agencies/my/agencies",
  agenciesJoin: "/api/agencies/join",
  agenciesLeave: "/api/agencies/leave",
  
  // LocalPro Plus Subscriptions
  localProPlusPlans: "/api/localpro-plus/plans",
  localProPlusPlanById: "/api/localpro-plus/plans",
  localProPlusSubscribe: "/api/localpro-plus/subscribe",
  localProPlusConfirmPayment: "/api/localpro-plus/confirm-payment",
  localProPlusCancel: "/api/localpro-plus/cancel",
  localProPlusRenew: "/api/localpro-plus/renew",
  localProPlusMySubscription: "/api/localpro-plus/my-subscription",
  localProPlusSettings: "/api/localpro-plus/settings",
  localProPlusUsage: "/api/localpro-plus/usage",
  localProPlusAnalytics: "/api/localpro-plus/analytics",
  // Admin Manual Subscriptions
  localProPlusAdminSubscriptions: "/api/localpro-plus/admin/subscriptions",
  localProPlusAdminSubscriptionByUser: "/api/localpro-plus/admin/subscriptions/user",
  localProPlusAdminSubscriptionById: "/api/localpro-plus/admin/subscriptions",
  
  // Settings Management
  settings: "/api/settings",
  settingsUser: "/api/settings/user",
  settingsUserCategory: "/api/settings/user",
  settingsUserReset: "/api/settings/user/reset",
  settingsUserDelete: "/api/settings/user",
  settingsApp: "/api/settings/app",
  settingsAppCategory: "/api/settings/app",
  settingsAppFeaturesToggle: "/api/settings/app/features/toggle",
  settingsAppPublic: "/api/settings/app/public",
  settingsAppHealth: "/api/settings/app/health",
  settingsAppUpdate: "/api/settings/app",
  
  // Analytics & Insights
  analyticsOverview: "/api/analytics/overview",
  analyticsUser: "/api/analytics/user",
  analyticsMarketplace: "/api/analytics/marketplace",
  analyticsJobs: "/api/analytics/jobs",
  analyticsReferrals: "/api/analytics/referrals",
  analyticsAgencies: "/api/analytics/agencies",
  analyticsTrack: "/api/analytics/track",
  
  // Broadcaster
  broadcaster: "/api/broadcaster",
  broadcasterById: "/api/broadcaster",
  broadcasterActive: "/api/broadcaster/active",
  broadcasterStats: "/api/broadcaster/stats",
  broadcasterView: "/api/broadcaster",
  broadcasterClick: "/api/broadcaster",
  analyticsRealTime: "/api/analytics/real-time",
  analyticsPerformance: "/api/analytics/performance",
  analyticsUserBehavior: "/api/analytics/user-behavior",
  analyticsRevenue: "/api/analytics/revenue",
  analyticsConversion: "/api/analytics/conversion",
  analyticsDashboard: "/api/analytics/dashboard",
  
  // Global Search
  search: "/api/search",
  searchSuggestions: "/api/search/suggestions",
  searchPopular: "/api/search/popular",
  searchAdvanced: "/api/search/advanced",
  searchEntities: "/api/search/entities",
  searchCategories: "/api/search/categories",
  searchLocations: "/api/search/locations",
  searchTrending: "/api/search/trending",
  searchAnalytics: "/api/search/analytics",
  
  // Announcements
  announcements: "/api/announcements",
  announcementsById: "/api/announcements",
  announcementsMyList: "/api/announcements/my/list",
  announcementsAcknowledge: "/api/announcements",
  announcementsComments: "/api/announcements",
  announcementsAdminStatistics: "/api/announcements/admin/statistics",
  
  // Activities & Discovery
  activitiesFeed: "/api/activities/feed",
  activitiesMy: "/api/activities/my",
  activitiesUser: "/api/activities/user",
  activitiesById: "/api/activities",
  activities: "/api/activities",
  activitiesInteractions: "/api/activities",
  activitiesStatsMy: "/api/activities/stats/my",
  activitiesStatsGlobal: "/api/activities/stats/global",
  activitiesMetadata: "/api/activities/metadata",
  activitiesUserById: "/api/activities/user/[userId]",
  activitiesStats: "/api/activities/stats",
  activitiesGlobalStats: "/api/activities/global/stats",

  // Logs & System Monitoring
  logs: "/api/logs",
  logsStats: "/api/logs/stats",
  logsUser: "/api/logs/user",
  logsUserActivity: "/api/logs/user/[userId]/activity",
  logsDashboardSummary: "/api/logs/dashboard/summary",
  logsAnalyticsPerformance: "/api/logs/analytics/performance",
  logsAnalyticsErrorTrends: "/api/logs/analytics/error-trends",
  logsSearchGlobal: "/api/logs/search/global",
  logsById: "/api/logs",
  logsExportData: "/api/logs/export/data",
  logsCleanup: "/api/logs/cleanup",
  logsFlush: "/api/logs/flush",
  
  // Audit Logs
  auditLogs: "/api/audit-logs",
  auditLogsStats: "/api/audit-logs/stats",
  auditLogsUserActivity: "/api/audit-logs/user/[userId]/activity",
  auditLogsById: "/api/audit-logs",
  auditLogsExportData: "/api/audit-logs/export/data",
  auditLogsDashboardSummary: "/api/audit-logs/dashboard/summary",
  auditLogsCleanup: "/api/audit-logs/cleanup",
  auditLogsMetadataCategories: "/api/audit-logs/metadata/categories",
  
  // Admin Audit Logs
  adminAuditLogs: "/api/admin/audit-logs",
  adminAuditLogsStats: "/api/admin/audit-logs/stats",
  adminAuditLogsUserActivity: "/api/admin/audit-logs/user/[userId]/activity",
  adminAuditLogsById: "/api/admin/audit-logs",
  adminAuditLogsExportData: "/api/admin/audit-logs/export/data",
  adminAuditLogsDashboardSummary: "/api/admin/audit-logs/dashboard/summary",
  adminAuditLogsCleanup: "/api/admin/audit-logs/cleanup",
  adminAuditLogsMetadataCategories: "/api/admin/audit-logs/metadata/categories",
  
  // Error Monitoring
  errorMonitoring: "/api/error-monitoring",
  errorMonitoringStats: "/api/error-monitoring/stats",
  errorMonitoringUnresolved: "/api/error-monitoring/unresolved",
  errorMonitoringById: "/api/error-monitoring",
  errorMonitoringResolve: "/api/error-monitoring",
  errorMonitoringDashboardSummary: "/api/error-monitoring/dashboard/summary",

  // User Management
  users: "/api/users",
  usersStats: "/api/users/stats",
  usersById: "/api/users",
  usersCreate: "/api/users",
  usersUpdate: "/api/users",
  usersStatus: "/api/users",
  usersVerification: "/api/users",
  usersBadges: "/api/users",
  usersBulk: "/api/users/bulk",
  usersDelete: "/api/users",

  registrationEarlyAccess: "/api/registration/early",
  
  // Favorites
  favorites: "/api/favorites",
  favoritesStats: "/api/favorites/stats",
  favoritesByType: "/api/favorites/type",
  favoritesCheck: "/api/favorites/check",
  favoritesById: "/api/favorites",
  favoritesByItem: "/api/favorites",
  
  // Monitoring Endpoints
  monitoringSystemHealth: "/api/monitoring/system-health",
} as const;
