// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/certifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/certifications">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/certifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/courses">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/create-course/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/create-course">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/create-course/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/instructors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/instructors">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/instructors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/my-courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/my-courses">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/my-courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/my-created-courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/my-created-courses">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/my-created-courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/[id]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads/[id]/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/[id]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads/create">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/@activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/@activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/@header/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/@header/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/@services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/@services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/@stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/@stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/empty-state-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/empty-state-demo">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/empty-state-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/facility-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facility-care">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/facility-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/jobs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/jobs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/jobs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/jobs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/ads">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/courses/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/courses/create">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/courses/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/courses">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/create-job/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/create-job">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/create-job/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/create-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/create-service">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/create-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/my-applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/my-applications">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/my-applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/my-bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/my-bookings">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/my-bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/my-jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/my-jobs">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/my-jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/my-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/my-services">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/my-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/provider/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/provider/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/provider/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/providers">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/rentals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/rentals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/rentals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/rentals">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/services/[id]/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/services/[id]/book">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/services/[id]/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/services/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/services/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/services/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/services/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/services/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/services/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/services/category/[key]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/services/category/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/services/category/[key]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/supplies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/supplies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/supplies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/supplies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/mpin/forgot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mpin/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/mpin/forgot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/mpin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mpin">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/mpin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/mpin/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mpin/setup">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/mpin/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/plus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plus">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/plus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/rentals/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/rentals/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/rentals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/rentals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/rentals/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/create">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/rentals/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/create">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/my-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/my-orders">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/my-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/my-supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/my-supplies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/my-supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/verified/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplies/verified">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/verified/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connect">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/help-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help-center">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/help-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/academy">> = Specific
  const handler = {} as typeof import("../../src/app/admin/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/activity">> = Specific
  const handler = {} as typeof import("../../src/app/admin/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agencies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/app-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app-settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/app-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/broadcaster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/broadcaster">> = Specific
  const handler = {} as typeof import("../../src/app/admin/broadcaster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication">> = Specific
  const handler = {} as typeof import("../../src/app/admin/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/database/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/database">> = Specific
  const handler = {} as typeof import("../../src/app/admin/database/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/email-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/email-marketing">> = Specific
  const handler = {} as typeof import("../../src/app/admin/email-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/errors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/errors">> = Specific
  const handler = {} as typeof import("../../src/app/admin/errors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../src/app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/health">> = Specific
  const handler = {} as typeof import("../../src/app/admin/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/live-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/live-chat">> = Specific
  const handler = {} as typeof import("../../src/app/admin/live-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/plus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plus">> = Specific
  const handler = {} as typeof import("../../src/app/admin/plus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/referrals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rentals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/supplies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/trust-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trust-verification">> = Specific
  const handler = {} as typeof import("../../src/app/admin/trust-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maintenance/bypass/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/bypass">> = Specific
  const handler = {} as typeof import("../../src/app/api/maintenance/bypass/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/ads/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ads">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/ads/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/agencies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agencies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/agencies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/marketplace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/marketplace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/rentals/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/rentals">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/rentals/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(authenticated)/supplies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/supplies">> = Specific
  const handler = {} as typeof import("../../src/app/(authenticated)/supplies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/careers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/careers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/community/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/community">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/community/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/help-center/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/help-center">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/help-center/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/security/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/security/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
